name: Continuous Integration

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev libpq-dev libsqlite3-dev lld
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev libpq-dev libsqlite3-dev lld
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Update package index
        run: sudo apt-get update -y
      - name: Install native dependencies
        run: sudo apt-get install -y libmysqlclient-dev libpq-dev libsqlite3-dev lld
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: make build-release
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux Build (x86_64)
          path: ./target/x86_64-unknown-linux-gnu/release/url_shortener

  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Build
        run: make build-release
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows Build (x86_64)
          path: ./target/release/url_shortener.exe
